package com.padelium.domain.dto

import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate

data class SaveBookingRequest(
    val aamount: BigDecimal,
    val amount: BigDecimal,
    val amountfeeTrans: BigDecimal,
    val bookingAnnulationDTOSet: List<bookingAnnulationDTOSet>,
    val isClient:Boolean = true,
    val closeTime: Instant,
    val couponCode: String,
    val currencyId:Long,
    val currencySymbol:String,
    val decimalNumber: Int,
    val description: String,
    val end: String,
    val Establishment: List<EstablishmentDTO>,
    val establishmentPacksDTO: List<EstablishmentPacksDTO>,
    val establishmentPacksId: Long,
    val establishmentPictureDTO: List<EstablishmentPictureDTO>,
    val facadeUrl: String,
    val from: Instant,
    val HappyHours: List<HappyHours>,
    val mgAmount: BigDecimal,
    val moyFeed: Double,
    val numberOfPart:Int,
    val numberOfPlayer: Int,
    val openTime: Instant = Instant.now(), // Default value
    val payFromAvoir: Boolean,
    val plannings: List<PlanningDTO>,
    val privateExtrasIds:List<Long>,
    val ramountfeeTrans: BigDecimal,
    val reduction: Int,
    val reductionAmount: BigDecimal,
    val reductionSecondAmount: BigDecimal,
    val reductionaAmount: BigDecimal,
    val reductionaSecondAmount: BigDecimal,
    val rsamountfeeTrans: BigDecimal,
    val samountfeeTrans: BigDecimal,
    val searchDate: LocalDate,
    val secondAamount: BigDecimal,
    val secondAmount: BigDecimal,
    val secondReduction: Int,
    val sharedExtrasIds: List<Long>,
    val start: String,
    val to: String,
    val totalFeed: Int,
    val users: List<Long>,
    val usersIds:List<Long>,
    val withSecondPrice: Boolean,

    )
{
    constructor() : this(
        aamount = BigDecimal.ZERO,
        amount = BigDecimal.ZERO,
        amountfeeTrans = BigDecimal.ZERO,
        bookingAnnulationDTOSet = emptyList(),
        closeTime = Instant.now(),
        couponCode = "",
        currencyId = 0L,
        currencySymbol = "",
        decimalNumber = 2,
        description = "",
        end = "",
        Establishment = emptyList(),
        establishmentPacksDTO = emptyList(),
        establishmentPacksId = 0L,
        establishmentPictureDTO = emptyList(),
        facadeUrl = "",
        from = Instant.now(),
        HappyHours = emptyList(),
        mgAmount = BigDecimal.ZERO,
        moyFeed = 0.0,
        numberOfPart = 0,
        numberOfPlayer = 0,
        openTime = Instant.now(),
        payFromAvoir = false,
        plannings = emptyList(),
        privateExtrasIds = emptyList(),
        ramountfeeTrans = BigDecimal.ZERO,
        reduction = 0,
        reductionAmount = BigDecimal.ZERO,
        reductionSecondAmount = BigDecimal.ZERO,
        reductionaAmount = BigDecimal.ZERO,
        reductionaSecondAmount = BigDecimal.ZERO,
        rsamountfeeTrans = BigDecimal.ZERO,
        samountfeeTrans = BigDecimal.ZERO,
        searchDate = LocalDate.now(),
        secondAamount = BigDecimal.ZERO,
        secondAmount = BigDecimal.ZERO,
        secondReduction = 0,
        sharedExtrasIds = emptyList(),
        start = "",
        to = "",
        totalFeed = 0,
        users = emptyList(),
        usersIds = emptyList(),
        withSecondPrice = false
    )
}
