package com.padelium.domain.dto

import java.math.BigDecimal
import java.time.Instant

data class SearchListResponse(

    val id: Long,
    val name: String,
    val code: String,
    val description: String?,
    val email: String?,
    val address: String?,
    val latitude: Double,
    val longitude: Double,
    val cityName: String,
    val activityName: String,
    val facadeUrl: String,
    val amount: Double,
    val currencyName: String,
    val decimalNumber: Int,
    val currencySymbol: String,
    val totalFeed: Int,
    val moyFeed: Double,
    val secondAmount: Double?,
    val numberOfPlayer: Int,
    val openTime: String?,
    val closedTime: String?,
    val reductionAmount: Double?,
    val reductionSecondAmount: Double?,
    val establishmentPictureDTO: List<EstablishmentPictureDTO>,
    val logo: String?,
    val key: String?,
    val timeSpan: Int,
    val createdDate: String,
    val establishmentId: Long,
    val client: Boolean,
    val plannings: List<PlanningDTO>,
    val to: Instant = Instant.now(),
    val available: Int = 0,
    val adress: String,
    val created: Instant,
    val updated: Instant,
    val createdBy: Long,
    val updatedBy: Long,
    val cityId: Long,
    val activityId: Long,
    val jhiEntityId: Long,
    val validated: Boolean,
    val maxNumberPlayer: Int,
    val userId: Long,
    val userEmail: String,
    val activityCode: String,
    val detailDescription: String,
    val activityValide: Boolean,
    val phone: String,
    val establishmentFeatureDTOList: List<establishmentFeatureDTO>,
    val contacts: List<contactDTO>,
    val createdByName: String,
    val createdByEmail: String,
    val pictures: List<Unit>,
    val facadePict: Boolean,
    val facadePict1: Boolean,
    val facadePict2: Boolean,
    val facadePict3: Boolean,
    val color: String,
    val establishmentTypeId: Long,
    val establishmentTypeCode: String,
    val isEvent: Boolean = false,
    val isSpace: Boolean = false,
    val showAsGold: Boolean = false,
    val activityActive: Boolean,
    val activitySmallIcon: String,
    val activityIcon: String,
    val isClient: Boolean = true,
    val from: Instant,
    val closeTime: Instant,
    val bookings: List<bookingDTO>,
    val availableBol: Boolean,
    val dayWithBooking: Boolean,
    val fromStr: String,
    val toStr: String,
    val price: BigDecimal,
    val feeTransaction: BigDecimal,
    val reductionPrice: BigDecimal,
    val rfeeTransaction: BigDecimal,
    val reductionPriceBol: Boolean,
    val secondPrice: Boolean,
    val isHappyHours: Boolean,
    val annulationDate: String,
)

