/*
class BookingDataTransformer {

    fun transform(response: GetBookingResponse): TransformedBookingData {
        return TransformedBookingData(
            establishmentDTO = response.establishmentDTO,
            amount = response.amount,
            decimalNumber = response.decimalNumber,
            currencySymbol = response.currencySymbol,
            facadeUrl = response.facadeUrl,
            openTime = response.openTime,
            closeTime = response.closeTime,
            searchDate = response.searchDate,
            from = response.from,
            to = response.to,
            numberOfPlayer = response.numberOfPlayer,
            description = response.description,
            currencyId = response.currencyId,
            mgAmount = response.mgAmount,
            totalFeed = response.totalFeed,
            moyFeed = response.moyFeed,
            bookingAnnulationDTOSet = response.bookingAnnulationDTOSet,
            secondAmount = response.secondAmount,
            secondAamount = response.secondAamount,
            key = response.key,
            HappyHours = response.HappyHours,
            withSecondPrice = response.withSecondPrice,
            reductionAmount = response.reductionAmount,
            reductionSecondAmount = response.reductionSecondAmount,
            payFromAvoir = response.payFromAvoir,
            reduction = response.reduction,
            reductionaAmount = response.reductionaAmount,
            reductionaSecondAmount = response.reductionaSecondAmount,
            start = response.start,
            end = response.end,
            amountfeeTrans = response.amountfeeTrans,
            samountfeeTrans = response.samountfeeTrans,
            ramountfeeTrans = response.ramountfeeTrans,
            rsamountfeeTrans = response.rsamountfeeTrans,
            couponCode = response.couponCode,
            establishmentPacksDTO = response.establishmentPacksDTO,
            establishmentPacksId = response.establishmentPacksId,
            plannings = response.plannings,
            users = response.users,
            isClient = response.isClient,
            secondReduction = response.secondReduction,
            aamount = response.aamount,
            EstablishmentPictureDTO = response.EstablishmentPictureDTO,
        )
    }
}*/